### ISSUE TITLE
npm start errors...

### ISSUE THREAD

**Issue by EtaySchur** [greatCodeIdeas/md-date-range-picker#1]
Hi There :)
Thx for this plugin ! it really looks great and has all the features im looking for ... 
I just cloned this project and tried to npm start it but it show some errors ... 
I did try to make my own project by using your example but for some reason some widgets are missing ( probably  CSS issues ) ... 
Am I missing something ? or its a known issue ? 
thanks alot again
Etay

**Comment by roelbarreto** [comment]
Hi @EtaySchur , you can try to remove node_modules directory and pull latest ang run npm install again,
Issue is caused by angular 1.6.x which has a big difference in angular 1.5.x, https://github.com/greatCodeIdeas/md-date-range-picker/commit/3ff3a2d7d6ec6bddce487906cf1ff6c580ad0d17

Regards
