### ISSUE TITLE
Disabled dates not working by selecting date range with template.

### ISSUE THREAD

**Issue by lnalbandyan** [greatCodeIdeas/md-date-range-picker#16]
@ipiz Hi, Thanks for adding disabled dates feature, we really appreciate that :) During tests I got some wired bug when selecting templates, it also selects disabled dates and in returned object we can see them. 
Would be great if you will fix that :) 

One more time thanks.

**Comment by roelbarreto** [comment]
Hmm that might a bit tricky as we need to filter also when you pass a start and end date on a model. 
I'll think of it on how to handle.

**Comment by lnalbandyan** [comment]
@ipiz Thanks

**Comment by roelbarreto** [comment]
For now Disabled dates should be handle by the controller when you received the returned date range model. When you disable all Sundays then you have Selected this week, it should select the week but displays that Sunday is grayed out but on your model you will need to tweak that the Sunday is not included.
