### ISSUE TITLE
How to disable the future dates? 

### ISSUE THREAD

**Issue by vishnu-vv** [greatCodeIdeas/md-date-range-picker#24]
If there is already an option to do this, please make the reference doc much more informative by including those options.

**Comment by roelbarreto** [comment]
Hi @vishnu-vv  Thanks for pointing out this. We already have this feature https://github.com/greatCodeIdeas/md-date-range-picker/blob/1a8cf8a8f82c44d6d35808711d35c5ebf611c7d0/demo/index.html#L44
We can add it to the docu.

```html
<md-date-range-picker is-disabled-date="isFuture($date)"></md-date-range-picker>
```
```javascript

$scope.isFuture= function ($date) {
   return $date.getTime() > new Date().getTime();
}
```

**Comment by roelbarreto** [comment]
Reference Commit
https://github.com/greatCodeIdeas/md-date-range-picker/commit/45cd579ede559d430409564f04eda9bcbb220861
https://github.com/greatCodeIdeas/md-date-range-picker/commit/93e99c62859df22ed3b22640e2b6e22b38f01457
