### ISSUE TITLE
Showing already selected dates

### ISSUE THREAD

**Issue by nirlepkaur** [greatCodeIdeas/md-date-range-picker#26]
Is there any options to highlight currently selected multiple date range, if Calendar UI is opened in edit mode. So if user has selected some date ranges and saved it, opening the UI, should show the already selected date ranges in Calendar

**Comment by bhargavmullakuru** [comment]
Set the date range start and end dates from the response to the mddaterangepicker's  scope variable..it will set the date range automatically..you can set on $scope.pick function too..

**Comment by nirlepkaur** [comment]
I need to display multiple selected date ranges in Calendar. So , user has selected a date range and saved it in database and performed this action few times. Now, opening the Calendar, need to highlight all those previously selected date ranges

**Comment by roelbarreto** [comment]
@nirlepkaur  If you want to display the previously selected date range saved into database you just need to pass it to the model. The following code might be how you want it.
```html
<md-date-range ng-model="selectedRange" placeholder="Select Date Range"></md-date-range>
```

 ```jaascript
$scope.selectedRange = {
  dateStart:  moment(startDateFromDB).toDate(),
  dateEnd: moment(endDateFromDB).toDate(),
};
```

Please let me know if this is not what you want.

But if you want to have a date range more than 1 range highlighted in the date picker, we don't have this functionality atm.
