### ISSUE TITLE
Picking dates with different years not working

### ISSUE THREAD

**Issue by ermin-islamagic** [greatCodeIdeas/md-date-range-picker#29]
![chrome_2017-10-04_19-01-55](https://user-images.githubusercontent.com/8225704/31188903-d57745ea-a936-11e7-84c1-74bf61e7e06b.png)

**Comment by roelbarreto** [comment]
Both bower and npm package Released version 0.6.2 for this Hotfix
Demo page updated https://ipiz.herokuapp.com/md-date-range-picker-demo/index.html
