### ISSUE TITLE
Rendering issue??

### ISSUE THREAD

**Issue by dharbinjaflick** [greatCodeIdeas/md-date-range-picker#3]
Hello,

Love the concept and am hoping to use your library in my project. One issue I'm having is that it's not rendering like your demos. I'm using the md-date-range directive. I have attached a screenshot of what it looks like for me:

<img width="351" alt="screen shot 2017-02-06 at 6 32 42 pm" src="https://cloud.githubusercontent.com/assets/9578924/22671165/e6a6fdaa-ec9a-11e6-9a6b-410e86ec1584.png">

Notice how the navigation (back, month, year, forward) seems to be rendered incorrectly. Have you seen this before?

I'm using latest (master) version of Angular Material however switching versions appeared to make no difference.

EDIT: I should also add that I have show-templates=true and I'm not seeing the templates either.

Thanks,
Dinko

**Comment by roelbarreto** [comment]
Please verify Fix on md-date-range-picker@0.3.1

**Comment by dharbinjaflick** [comment]
@ipiz Yup, looks fixed in the latest version. Thank you!
