### ISSUE TITLE
One specific day repeating on all days

### ISSUE THREAD

**Issue by danillocesar** [greatCodeIdeas/md-date-range-picker#30]
Hello, its me again.

With the new update, one of the days is showing as all days of the current month (just on firefox)

![image](https://user-images.githubusercontent.com/20955833/31227008-a4a3c29a-a9ae-11e7-98b4-4785fa7b4c43.png)

**Comment by roelbarreto** [comment]
@danillocesar  Can you verify again this on your firefox browser? regards...
Please check on the new Demo page https://ipiz.herokuapp.com/md-date-range-picker-demo/index.html

**Comment by danillocesar** [comment]
Its working fine now, i guess. Thank you @ipiz. if i find any more problem i will make sure to post it
