### ISSUE TITLE
When month starts on a Sunday, first-day-of-week>0 hides first days of month

### ISSUE THREAD

**Issue by jonaskoelker** [greatCodeIdeas/md-date-range-picker#31]
When a month starts on a Sunday, such as October 2017, and I set `first-day-of-week="1"`, the first date in the grid is October 2nd. I would expect a row with October 1st and the last six days of September being shown (the days of September being low-lighted).

**Comment by roelbarreto** [comment]
@jonaskoelker the issue should be reolved on 0.7.0 release
