### ISSUE TITLE
Feature request: number of days on selected range

### ISSUE THREAD

**Issue by ermin-islamagic** [greatCodeIdeas/md-date-range-picker#34]
Maybe to put number of days inclusive and or exclusive when 2 dates are picked ???

**Comment by roelbarreto** [comment]
referenced #32

**Comment by roelbarreto** [comment]
Hi @hamleet  with new 0.7.0 release we can now able to get all selectedDates and you can get the length for the counts

`<md-date-range md-on-select="countModel = $dates.length" ...`
