### ISSUE TITLE
Customisation 

### ISSUE THREAD

**Issue by louisdauvois** [greatCodeIdeas/md-date-range-picker#35]
Hi,

First of all thanks for the good work.

I have some question : 
- How to change the local ? I see the localmap but what is the format of this input.
- How I can change the color of the selected range ?

Thanks you

**Comment by roelbarreto** [comment]
- Local customization https://github.com/greatCodeIdeas/md-date-range-picker/issues/12
- You can override css styling, please check the applicable classes https://github.com/greatCodeIdeas/md-date-range-picker/blob/master/dist/md-date-range-picker.css

**Comment by roelbarreto** [comment]
I'll add an option to Customize The Display Format
