### ISSUE TITLE
open mdDateRange instead of mdDateRangePicker

### ISSUE THREAD

**Issue by ashishyadav0019** [greatCodeIdeas/md-date-range-picker#38]
Is there a way to open "mdDateRange" on button click or any other event (the one that opens in md-menu). instead of "mdDateRangePicker" (this one open in md-dialog)?

the documentation only has work around for "mdDateRangePicker"
```
$scope.selectDateRange = function () {
  $mdDateRangePicker.show({
    model: $scope.serviceModel,
  }).then(function (result) {
    $scope.serviceModel = result;
  }).catch(function () {
    console.log('Cancelled');
  }
}
```
    this on opens in dialog box...
but i want the one that opens in `md-menu` to open on my event

![md-dialog](https://user-images.githubusercontent.com/31069071/32741759-56914f30-c8cd-11e7-9feb-5b3be058e4b4.PNG)
![md-menu](https://user-images.githubusercontent.com/31069071/32741760-56d5388a-c8cd-11e7-8cd6-bb5fa3ff8f03.PNG)

Please help..
Thanks in advance

**Comment by roelbarreto** [comment]
Try something like this https://jsfiddle.net/xvc93tgs/1/
Or just put some css on the md-date-range button/input

**Comment by ashishyadav0019** [comment]
Thanks it just the thing i wanted....
I was trying to execute `$mdOpenMenu($event)` form out side of.... `mdMenu `that's the reason I failed.

Thanks a lot...
Made my day
