### ISSUE TITLE
firstDayOfWeek option doesn't work

### ISSUE THREAD

**Issue by aaronmoller** [greatCodeIdeas/md-date-range-picker#5]
I could not get the firstDayOfWeek option to work. Modifying START_OF_WEEK on md-date-range-picker.js,128 does work, so it looks like there's a bug in the assignment when the directive is set up. Am I missing something?

**Comment by roelbarreto** [comment]
Can you verify fix on the latest version 0.3.2 05fb19fe0b9ae3e6f5b63fe34183426d4954b155
regards.
`first-day-of-week="1"`

**Comment by aaronmoller** [comment]
How do I use it when calling the date picker with JS?

`$mdDateRangePicker.show({
                targetEvent: $event,
                model: $scope.selectedRange,
                firstDayofWeek: 0
            })`

**Comment by roelbarreto** [comment]
@aaronmoller Thanks for reporting this, i have released a new fix to include firstDayOfWeek on modal picker 
md-date-range-picker@0.3.3
```
// code here...
$scope.selectedRange.firstDayOfWeek = 0;
$mdDateRangePicker.show({ targetEvent: $event, model: $scope.selectedRange })
```
