### ISSUE TITLE
Setting start date time to end of day

### ISSUE THREAD

**Issue by fnnek** [greatCodeIdeas/md-date-range-picker#52]
Line 150, there's $scope.dateEnd && $scope.**dateStart**.setHours(23, 59, 59, 999); 
instead of $scope.dateEnd && $scope.**dateEnd**.setHours(23, 59, 59, 999); 

It couses troubles when you want to set start date at start.

**Comment by roelbarreto** [comment]
this should be
```$scope.dateEnd && $scope.dateEnd.setHours(23, 59, 59, 999);```
Thanks @fnnek  for pointing this out. I'll have a patch or you can do PR
