### ISSUE TITLE
Customisation of selected date

### ISSUE THREAD

**Issue by kyblinh** [greatCodeIdeas/md-date-range-picker#54]
Hi there,
I am trying to use the date picker and I would like to have a different format when range is selected. (My users do not want to see english). I would like to have something like '05/11/2018 - 26/12/2018'.

I cannot see how i could customize it that way , i have been able to translate most of the calendar with the localizationMap but I cannot get this to work.

Could you tell me how to achieve this?

Code is pretty simple so far: 

```
       <md-date-range
                ng-model="vm.filters.appointmentDateRange" localization-map="vm.localizationMap" >
            </md-date-range>
```

and

```
vm.localizationMap = {
			'Mon': 'Lu',
			'Tue': 'Ma',
			'Wed': 'Me',
			'Thu': 'Je',
			'Fri': 'Ve',
			'Sat': 'Sa',
			'Sun':'Dim',
			'This Week': 'Settimana corrente',
			"January": "Janvier",
			"February": "Février",
			"March": "Mars",
			"April": "Avril",
			"May": "Mai",
			"June": "Juin",
			"July": "Juillet",
			"August": "Aout",
			"September": "Septembre",
			"October": "Octobre",
			"November": "November",
			"December": "Decembre"
		};

		vm.filters =
		{
			appointmentDateRange: {
				//selectedTemplate: 'TY',
				//selectedTemplateName: 'Anno corrente',
				dateStart: new Date(),
				dateEnd: new Date(),
			}
		};
```

![date 1](https://user-images.githubusercontent.com/38066973/38297393-9972f790-37f4-11e8-9711-9a12984e4b18.png)
![date 2](https://user-images.githubusercontent.com/38066973/38297394-998c2102-37f4-11e8-93d3-30effa7db1e8.png)

Thanks for the help and for the good work :)

**Comment by roelbarreto** [comment]
You can customize the date selection display https://ipiz.herokuapp.com/md-date-range-picker-demo/index.html
Please see in Demo Advance

```javascript

$scope.format = function (dateStart, dateEnd, template, templateName) {
  return dateStart && dateEnd && (dateStart.toLocaleDateString() + ' - ' + dateEnd.toLocaleDateString());
 }

```
```html
<md-date-range format="format"></md-date-range>
```

![image](https://user-images.githubusercontent.com/1954163/38298075-3773861e-37ee-11e8-9105-4035fa311ac8.png)

**Comment by kyblinh** [comment]
Oh, i will do that. Sorry didn't see it... Thanks a lot!
