### ISSUE TITLE
Add the possibility to use different languages

### ISSUE THREAD

**Issue by tobiasAuzmendi** [greatCodeIdeas/md-date-range-picker#58]
Hi how that's going? 
I'm using the md-date-range-picker component. I'm wondering if is possible to use different languages. Is there a workaround to do this? I think that set the lang as some param is not the unique way, could be great, at least, set the month names, week day names and filtering options (such as "last month", "this year", etc..) verbiages settable. I'll appreciate an answer. 
Kind regards.

**Comment by roelbarreto** [comment]
Duplicate issue and feature already added by @yoni12ab , please refer to #6

**Comment by tobiasAuzmendi** [comment]
Great @ipiz! I'm playing with this. But as far as I understud the added functionality is related to custom templates (such as "last month", "this year", etc..). I can't find a way to translate week day names and month names. It would be very helpful for me to know your opinion about this. Thanks!

**Comment by roelbarreto** [comment]
Yes the Month and Days can be set on there too.
https://jsfiddle.net/xvc93tgs/3/

**Comment by tobiasAuzmendi** [comment]
Very complete and usable. Great job man!
