### ISSUE TITLE
Remove This year and Last Year options

### ISSUE THREAD

**Issue by manmarziyan** [greatCodeIdeas/md-date-range-picker#59]
I'm using a custom template along with the given template. I'd like to have day, week, month and 6 months options. Is there any way I can hide/remove the Year button?

**Comment by roelbarreto** [comment]
You can use the disableTemplates/disable-templates property

**Comment by roelbarreto** [comment]
Here is the example https://jsfiddle.net/ipiz/fav9mu0e/
```html 
<md-date-range disable-templates="['TY','LY']" show-template="true" ng-model="model" placeholder="Select Date Range"></md-date-range>```

**Comment by manmarziyan** [comment]
Works! Thanks

**Comment by vishnu-vv** [comment]
👍
